# Ruby CircleCI 2.0 configuration file
#
# Check https://circleci.com/docs/2.0/language-ruby/ for more details
#
version: 2
jobs:
  build:
    docker:
      # specify the version you desire here
       - image: circleci/ruby:2.4.1-node-browsers
      
      # Specify service dependencies here if necessary
      # CircleCI maintains a library of pre-built images
      # documented at https://circleci.com/docs/2.0/circleci-images/
      # - image: circleci/postgres:9.4

    working_directory: ~/repo
    output_directory: ./output

    steps:
      - checkout

      # Download and cache dependencies
      - restore_cache:
          keys:
          - v1-dependencies-{{ checksum "Gemfile.lock" }}
          # fallback to using the latest cache if no exact match is found
          - v1-dependencies-

      - run:
          name: install dependencies
          command: |
            bundle install --jobs=4 --retry=3 --path vendor/bundle

      - save_cache:
          paths:
            - ./vendor/bundle
          key: v1-dependencies-{{ checksum "Gemfile.lock" }}
        
      
      # run tests!
      - run:
          name: Run test and generate json results
          command: |
            mkdir -p ${output_directory}
            bundle exec cucumber --out=${output_directory}
          when: always
      - store_test_results:
          path: ${output_directory}
      - store_artifacts:
          path: ${output_directory}

      - run:
          name: Convert json results to html report
          command: |
            bundle exec report_builder -s ${output_directory} --out=${output_directory}
          when: always
      - store_test_results:
          path: ${output_directory}
      - store_artifacts:
          path: ${output_directory}
